DEFAULT_MODE = False
MODE_OFF = 0
MODE_ON = 1
DEFAULT_SPEED = 0
DEFAULT_ANGLE = 0

BTN_REQUEST_VALIDATE = "validate"
BTN_REQUEST_STOP = "stop"
BTN_REQUEST_DISCONNECT = "disconnect"

FRONT_PI_IP = "192.168.50.133"
RIGHT_PI_IP = "192.168.50.XX"
BACK_PI_IP = "192.168.50.XX"
LEFT_PI_IP = "192.168.50.XX"

SENSOR_BRIGHTPI = "bright-pi"
SENSOR_CAMERA = "camera"
SENSOR_FLYINGFISH = "flying-fish"

CHART_PATH = "static/img/"
CHART_NAME = "chart.jpg"

GPIO_FLYING_FISH_FRONT_RIGHT = 17
NAME_FLYING_FISH_FRONT_RIGHT = "Détecteur avant droit"
GPIO_FLYING_FISH_FRONT_LEFT = 23
NAME_FLYING_FISH_FRONT_LEFT = "Détecteur avant gauche"

CODE_TURN_NOTHING = 0
CODE_TURN_LEFT = 1
CODE_TURN_RIGHT = 2

CODE_MOVE_NOTHING = 0
CODE_MOVE_FORWARD = 1
CODE_MOVE_BACKWARD = 2

GPIO_FLYING_FISH = [
    (GPIO_FLYING_FISH_FRONT_LEFT, NAME_FLYING_FISH_FRONT_LEFT),
    (GPIO_FLYING_FISH_FRONT_RIGHT, NAME_FLYING_FISH_FRONT_RIGHT),
]