name: Publish mpy-cross web assembly package

on:
  push:
    tags:
    - '@pybricks/mpy-cross-**'

jobs:
  npm_mpy_cross:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: npm/mpy-cross
    steps:
    - uses: mymindstorm/setup-emsdk@v7
      with:
        version: 1.39.12
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install
    - run: yarn build
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
