name: Publish firmware package

on:
  push:
    tags:
    - '@pybricks/firmware/**'

jobs:
  npm_firmware:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: npm/firmware
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - run: python -m pip install PyGithub
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install
    - run: yarn build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
